[workspace]
members = [

    "password_backend"
, "core"]

resolver = "2"

[workspace.dependencies]
aes-gcm = { version = "0.10.3", features = ["zeroize"] }
argon2 = "0.5.3"
sqlx = { version = "0.8.6", features = ["sqlite"]}
