[package]
name = "password_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["zeroize"] }
argon2 = "0.5.3"
tokio = { version = "1.49.0", features = ["full"] }
sqlx = {workspace = true}
